- name: Deploy application to Kubernetes
  hosts: localhost
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Apply Kubernetes manifests
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', '/home/ubuntu/jenkins/workspace/ansible-deploy/kubernetes-manifest.yml') }}"

