- name: Deploy application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifest
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', '/home/ubuntu/jenkins/workspace/my-eks-deployment/kubernetes-manifest.yml') }}"

