- name: Deploy application to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes manifests
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition: "{{ lookup('file', 'kubernetes-manifest.yml') }}"

